apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/priyanshu3103/dev-argocd.git
    targetRevision: master
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Resource filters - what root app can manage
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status