# ============ JENKINS CASC CONFIG ============
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  namespace: jenkins
data:
  plugins.txt: |
    oic-auth:latest
    role-strategy:latest
    configuration-as-code:latest
    git:latest
    workflow-aggregator:latest
    kubernetes:latest
  jenkins.yaml: |
    jenkins:
      securityRealm:
        oic:
          clientId: "jenkins"
          clientSecret: "jenkins-dex-secret"
          wellKnownOpenIDConfigurationUrl: "https://argocd.localhost/api/dex/.well-known/openid-configuration"
          userNameField: "preferred_username"
          fullNameFieldName: "name"
          groupsFieldName: "groups"
          scopes: "openid email profile groups"
          disableSslVerification: true
      authorizationStrategy:
        roleBased:
          roles:
            global:
              - name: "admin"
                permissions:
                  - "Overall/Administer"
                assignments:
                  - "priyanshu3103"
              - name: "readonly"
                permissions:
                  - "Overall/Read"

---
# ============ SERVICE ACCOUNT ============
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins

---
# ============ CLUSTER ROLE BINDING ============
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins

---
# ============ PVC ============
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
# ============ DEPLOYMENT ============
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins

    spec:
      serviceAccountName: jenkins
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

      securityContext:
        fsGroup: 1000
        runAsUser: 1000

      initContainers:

        - name: fix-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]

          securityContext:
            runAsUser: 0

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

        - name: install-plugins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - jenkins-plugin-cli --plugin-file /var/jenkins_casc/plugins.txt

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

            - name: jenkins-casc
              mountPath: /var/jenkins_casc

      containers:

        - name: jenkins
          image: priyanshu30/jenkins-mysql:lts_v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP

          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m -Djenkins.install.runSetupWizard=false"

            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_casc/jenkins.yaml

          resources:
            requests:
              cpu: 500m
              memory: 512Mi

            limits:
              cpu: 1000m
              memory: 1Gi

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

            - name: jenkins-casc
              mountPath: /var/jenkins_casc

          readinessProbe:
            httpGet:
              path: /login
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10

      volumes:

        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc

        - name: jenkins-casc
          configMap:
            name: jenkins-casc

---
# ============ SERVICE ============
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000