apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://35.81.148.199:31693
# Auto reload config every 10 seconds
  timeout.reconciliation: 10s
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23limd3PFv9mcPHlaY
        clientSecret: c860c65d15da56644f4238c7c5b2743fab23b5ab
        # Remove orgs block completely ← 
        loadAllGroups: false
        useLoginAsID: true
        