apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly

  policy.csv: |
    # Admin role - full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow

    # Jenkins dev role - jenkins namespace only
    p, role:jenkins-dev, applications, get, jenkins-project/*, allow
    p, role:jenkins-dev, applications, sync, jenkins-project/*, allow
    p, role:jenkins-dev, applications, action/*, jenkins-project/*, allow

    # Readonly role - view only
    p, role:readonly, applications, get, */*, allow

  scopes: '[groups, email]'