apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Auto reload dex config without restart
  server.dex.server.disable.tls: "true"
  reposerver.parallelism.limit: "10"
  