apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/priyanshu3103/dev-argocd.git
        revision: master
        directories:
          - path: apps/*
            exclude: true
          - path: apps/argocd

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/priyanshu3103/dev-argocd.git
        targetRevision: master
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true