apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/priyanshu3103/dev-argocd.git
    targetRevision: master
    path: apps/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false        # ← never delete argocd default cms
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      # ← avoids conflict with argocd managed fields
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: argocd-cm
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/annotations
    - group: ""
      kind: ConfigMap
      name: argocd-rbac-cm
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/annotations
    - group: ""
      kind: ConfigMap
      name: argocd-cmd-params-cm
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/annotations