apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Jenkins Project
  sourceRepos:
    - https://github.com/priyanshu3103/*
  destinations:
    - server: https://kubernetes.default.svc
      namespace: jenkins
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"