apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: jenkins-rules
  source:
    repoURL: https://github.com/priyanshu3103/argocd-manifests
    targetRevision: HEAD
    path: apps/jenkins        # ← ArgoCD reads all yaml files in folder
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true