controller:
  serviceType: NodePort

  adminUser: admin
  adminPassword: admin123

  installPlugins:
    - kubernetes
    - workflow-job
    - git
    - configuration-as-code
    - blueocean

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

persistence:
  enabled: true
  size: 5Gi

agent:
  enabled: true