frontend:
  enabled: true
  image:
    repository: priyanshu30/jenkins-agent-frontend
    tag: master-08fa476 # frontend    # ← comment needed for sed to find correct line
    pullPolicy: Always
  port: 80
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

backend:
  enabled: true
  image:
    repository: priyanshu30/jenkins-agent-backend
    tag: master-08fa476 # backend    # ← comment needed for sed to find correct line
    pullPolicy: Always
  port: 8000
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

namespace: jenkins

config:
  jenkinsUrl: "http://jenkins:8080"    # ← internal
  frontendUrl: "http://agent.localhost"
  backendUrl: "http://jenkins-agent-backend:8000"