# apiVersion: v1
# kind: Secret
# metadata:
#   name: jenkins-agent-secrets
#   namespace: {{ .Values.namespace }}
# type: Opaque
# stringData:
#   AGENT_API_KEY: {{ .Values.secrets.agentApiKey }}
#   JENKINS_CREDS: {{ .Values.secrets.jenkinsToken }}
#   SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl }}