argo-cd:
  global:
    domain: argocd.devops

  server:
    service:
      type: ClusterIP    # ← change to ClusterIP since using ingress
      certificate:
      enabled: true
      domain: argocd.localhost
      issuer:
        kind: ClusterIssuer
        name: selfsigned

    extraArgs:
      - --insecure    # ← ArgoCD HTTP internally

    config:
      url: https://argocd.devops
      timeout.reconciliation: 10s
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Ov23limd3PFv9mcPHlaY
              clientSecret: 3a94802f87d9b53a6e793387d6278dfed7094e56
              loadAllGroups: false
              useLoginAsID: true
              redirectURI: https://argocd.devops/api/dex/callback
        staticClients:
          - id: jenkins
            name: Jenkins
            secret: jenkins-dex-secret
            redirectURIs:
              - http://jenkins.localhost/securityRealm/finishLogin

    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow
        p, role:admin, accounts, *, *, allow
        p, role:admin, gpgkeys, *, *, allow
        g, priyanshu3103, role:admin
      scopes: '[groups, email]'

  dex:
    enabled: true

  redis:
    enabled: true

  repoServer:
    autoscaling:
      enabled: false

  applicationSet:
    enabled: true

  notifications:
    enabled: false